USE customer_behaviour;
GO

/*
===============================================================================
Q1. What is the total revenue generated by male vs. female customers?
===============================================================================
*/

SELECT
    Gender,
    SUM(Purchase_Amount_USD) AS Revenue
FROM dbo.customer_shopping_behavior
GROUP BY Gender;



/*
===============================================================================
Q2. Which customers used a discount but still spent more than the average
purchase amount?
===============================================================================
*/

SELECT
    Customer_ID,
    Purchase_Amount_USD
FROM dbo.customer_shopping_behavior
WHERE Discount_Applied = 'Yes'
AND Purchase_Amount_USD >
(
    SELECT AVG(Purchase_Amount_USD)
    FROM dbo.customer_shopping_behavior
);



/*
===============================================================================
Q3. Which are the top 5 products with the highest average review rating?
===============================================================================
*/

SELECT TOP 5
    Item_Purchased,
    ROUND(AVG(Review_Rating),2) AS Average_Product_Rating
FROM dbo.customer_shopping_behavior
GROUP BY Item_Purchased
ORDER BY Average_Product_Rating DESC;



/*
===============================================================================
Q4. Compare the average purchase amount between Standard and Express Shipping.
===============================================================================
*/

SELECT
    Shipping_Type,
    ROUND(AVG(Purchase_Amount_USD),2) AS Average_Purchase
FROM dbo.customer_shopping_behavior
WHERE Shipping_Type IN ('Standard','Express')
GROUP BY Shipping_Type;



/*
===============================================================================
Q5. Compare subscribers vs. non-subscribers by average spend and total revenue.
===============================================================================
*/

SELECT
    Subscription_Status,
    COUNT(Customer_ID) AS Total_Customers,
    ROUND(AVG(Purchase_Amount_USD),2) AS Average_Spend,
    SUM(Purchase_Amount_USD) AS Total_Revenue
FROM dbo.customer_shopping_behavior
GROUP BY Subscription_Status
ORDER BY Total_Revenue DESC;



/*
===============================================================================
Q6. Which 5 products have the highest percentage of discounted purchases?
===============================================================================
*/

SELECT TOP 5
    Item_Purchased,
    ROUND(
        100.0 *
        SUM(CASE
                WHEN Discount_Applied='Yes' THEN 1
                ELSE 0
            END) / COUNT(*),
        2
    ) AS Discount_Rate
FROM dbo.customer_shopping_behavior
GROUP BY Item_Purchased
ORDER BY Discount_Rate DESC;



/*
===============================================================================
Q7. Segment customers into New, Returning and Loyal.
===============================================================================
*/

WITH CustomerType AS
(
    SELECT
        Customer_ID,
        Previous_Purchases,
        CASE
            WHEN Previous_Purchases = 1 THEN 'New'
            WHEN Previous_Purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS Customer_Segment
    FROM dbo.customer_shopping_behavior
)

SELECT
    Customer_Segment,
    COUNT(*) AS Number_of_Customers
FROM CustomerType
GROUP BY Customer_Segment
ORDER BY Number_of_Customers DESC;



/*
===============================================================================
Q8. Top 3 most purchased products within each category.
===============================================================================
*/

WITH ItemCounts AS
(
    SELECT
        Category,
        Item_Purchased,
        COUNT(*) AS Total_Orders,
        ROW_NUMBER() OVER
        (
            PARTITION BY Category
            ORDER BY COUNT(*) DESC
        ) AS Item_Rank
    FROM dbo.customer_shopping_behavior
    GROUP BY Category, Item_Purchased
)

SELECT
    Item_Rank,
    Category,
    Item_Purchased,
    Total_Orders
FROM ItemCounts
WHERE Item_Rank <= 3
ORDER BY Category, Item_Rank;



/*
===============================================================================
Q9. Are repeat buyers (more than 5 purchases) likely to subscribe?
===============================================================================
*/

SELECT
    Subscription_Status,
    COUNT(Customer_ID) AS Repeat_Buyers
FROM dbo.customer_shopping_behavior
WHERE Previous_Purchases > 5
GROUP BY Subscription_Status;



/*
===============================================================================
Q10. Revenue contribution by age group.
===============================================================================
*/

SELECT
    CASE
        WHEN Age BETWEEN 18 AND 29 THEN 'Young Adult'
        WHEN Age BETWEEN 30 AND 44 THEN 'Adult'
        WHEN Age BETWEEN 45 AND 59 THEN 'Middle-aged'
        ELSE 'Senior'
    END AS Age_Group,

    SUM(Purchase_Amount_USD) AS Total_Revenue

FROM dbo.customer_shopping_behavior

GROUP BY
    CASE
        WHEN Age BETWEEN 18 AND 29 THEN 'Young Adult'
        WHEN Age BETWEEN 30 AND 44 THEN 'Adult'
        WHEN Age BETWEEN 45 AND 59 THEN 'Middle-aged'
        ELSE 'Senior'
    END

ORDER BY Total_Revenue DESC;